steps:
  - uses: ros-tooling/setup-ros@v0.2
    with:
      required-ros-distributions: melodic
  - uses: ros-tooling/action-ros-ci@v0.2
    with:
      package-name: music_state_machine
      target-ros1-distro: melodic
