name: Greetings
on: [push]
jobs:
  Greet:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Since this is a hardware project, it requires a self hosted 
    CI/CD pipeline connected with required hardware"
